<?php try { ?>
    <?php
    /* @var $this DigitalDataLayer_Block_Ddl */
    $triggered_messaging_digital_data_layer_enabled = Mage::getStoreConfig('digital_data_layer/enabled');

    $observer = 'digital_data_layer_main/page_observer';
    $mage = Mage::getSingleton($observer);
    ?>
    <?php if ($triggered_messaging_digital_data_layer_enabled == 1) : ?>
        <?php
        // extract variable only when digital data layer is enabled
        $version = $mage->getVersion();
        $page = $mage->getPage();
        $user = $mage->getUser();
        $product = $mage->getProduct();
        $cart = $mage->getCart();
        $listing = $mage->getListing();
        $transaction = $mage->getTransaction();
        $events = $mage->getEvents();
        $pluginVersion = (string)Mage::getConfig()->getNode()->modules->DigitalDataLayer->version;
        $timeStamp = time() * 1000;
        ?>
        <?php
        try {
            // Extract things only available within template (and not model)
            if (!$page['pageInfo']) {
                $page['pageInfo'] = array();
            }
            if (!$page['pageInfo']['pageName'] || $page['pageInfo']['pageName'] === '') {
                $page['pageInfo']['pageName'] = $this->getLayout()->getBlock('head')->getTitle();
            } else {
                unset($page['pageInfo']['pageName']);
            }
        } catch (Exception $e) {
        }
        ?>
        <!-- W3C Digital Data Layer Start -->
        <script type="text/javascript">
            try {
                window.digitalData = window.digitalData || {};
                window.digitalData.version = <?php echo json_encode($version); ?>;
                window.digitalData.page = <?php echo json_encode($page); ?>;
                window.digitalData.user = <?php echo json_encode($user); ?>;
                <?php if ($product) : ?>
                window.digitalData.product = <?php echo json_encode($product) ?>;
                <?php endif; ?>
                <?php if ($cart) : ?>
                window.digitalData.cart = <?php echo json_encode($cart) ?>;
                <?php endif; ?>
                <?php if ($listing): ?>
                window.digitalData.listing = <?php echo json_encode($listing) ?>;
                <?php endif; ?>
                <?php if ($transaction): ?>
                window.digitalData.transaction = <?php echo json_encode($transaction) ?>;
                <?php endif; ?>
                <?php if ($events): ?>
                window.digitalData.events = <?php echo json_encode($events); ?>;
                <?php endif; ?>
                <?php if ($pluginVersion): ?>
                window.digitalData.pluginVersion = <?php echo json_encode($pluginVersion); ?>;
                <?php endif; ?>
                <?php if ($timeStamp): ?>
                window.digitalData.generatedDate = <?php echo json_encode($timeStamp); ?>;
                <?php endif; ?>
            } catch (e) {
            }
        </script>
        <!-- W3C Digital Data Layer End -->
    <?php endif; ?>

<?php } catch (Exception $e) {
} ?>
